<?php

namespace Pterodactyl\Services\Proxy;

use Pterodactyl\Models\ServerSubdomain;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\File;

class HaproxyService
{
    /**
     * Generate HAProxy configuration for a subdomain.
     * 
     * This generates a backend configuration that will be included in the main HAProxy config.
     */
    public function generateBackendConfig(ServerSubdomain $subdomain): string
    {
        $server = $subdomain->server;
        $allocation = $server->allocation;

        if (!$allocation) {
            throw new \Exception('Server does not have an allocation.');
        }

        // For HAProxy, we need to connect to the container.
        // If the allocation IP is 0.0.0.0, use localhost since the container is on the same host.
        $allocationIp = $allocation->ip;
        $containerIp = ($allocationIp === '0.0.0.0' || $allocationIp === '::') ? '127.0.0.1' : $allocationIp;
        $containerPort = $allocation->port;
        $hostname = $subdomain->full_domain;

        $config = <<<HAPROXY
# Backend for subdomain: {$hostname}
# Subdomain ID: {$subdomain->id}
# Server ID: {$server->id}
# Generated: {$subdomain->updated_at->toIso8601String()}
# Routes: {$hostname} -> {$containerIp}:{$containerPort}

backend subdomain_{$subdomain->id}_backend
    mode tcp
    server container_{$subdomain->id} {$containerIp}:{$containerPort} check inter 3s fall 3 rise 2

HAPROXY;

        return $config;
    }

    /**
     * Generate the complete HAProxy configuration including all active subdomains.
     */
    public function generateFullConfig(): string
    {
        $subdomains = \Pterodactyl\Models\ServerSubdomain::where('is_active', true)
            ->whereNotNull('proxy_port')
            ->with(['server.allocation', 'domain'])
            ->get();

        $defaultProxyPort = config('proxy.default_proxy_port', 25565);
        $inspectDelay = config('proxy.haproxy_inspect_delay', 5);
        $defaultBackend = config('proxy.haproxy_default_backend');

        // Build frontend ACL rules and backend definitions
        // Note: In Phase 3, we'll use Lua script to extract hostname from Minecraft packet
        // For now, we set up the structure with placeholder ACLs
        $frontendAcls = '';
        $backendDefs = '';

        if ($subdomains->isEmpty()) {
            $frontendAcls = "    # No subdomains configured yet\n";
            $frontendAcls .= "    # Add a subdomain with proxy_port to enable routing\n";
        } else {
            foreach ($subdomains as $subdomain) {
                $hostname = $subdomain->full_domain;
                $backendName = "subdomain_{$subdomain->id}_backend";
                
                // Add ACL rule for this hostname using Lua fetch function
                // The Lua script extracts the hostname from the Minecraft handshake packet
                // Note: The fetch is registered as "minecraft_hostname", so it's accessed as lua.minecraft_hostname
                $frontendAcls .= "    # ACL for {$hostname}\n";
                $frontendAcls .= "    use_backend {$backendName} if { lua.minecraft_hostname -m str {$hostname} }\n";
                
                // Generate backend config
                $backendDefs .= $this->generateBackendConfig($subdomain);
            }
        }

        // Default backend (if configured and exists)
        $defaultBackendLine = '';
        if ($defaultBackend) {
            // Verify the default backend actually exists in our backends
            $backendExists = false;
            foreach ($subdomains as $subdomain) {
                if ("subdomain_{$subdomain->id}_backend" === $defaultBackend) {
                    $backendExists = true;
                    break;
                }
            }
            
            if ($backendExists) {
                $defaultBackendLine = "    default_backend {$defaultBackend}\n";
            } else {
                // Default backend doesn't exist, log warning and don't use it
                Log::warning('Default backend specified but does not exist', [
                    'default_backend' => $defaultBackend,
                    'available_backends' => $subdomains->map(fn($s) => "subdomain_{$s->id}_backend")->toArray(),
                ]);
                $defaultBackendLine = "    # Default backend '{$defaultBackend}' not found - connections that don't match will be rejected\n";
            }
        } else {
            $defaultBackendLine = "    # No default backend - connections that don't match any subdomain will be rejected\n";
        }

        $config = <<<HAPROXY
# HAProxy Configuration for Pyrodactyl Subdomain Proxy
# Auto-generated - Do not edit manually
# Generated: {$this->getCurrentTimestamp()}
# 
# WARNING: This file is automatically generated. Manual edits will be overwritten.
# To customize, modify the Laravel configuration files instead.

global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon
    maxconn 4096
    # Lua script for Minecraft protocol parsing
    lua-load /etc/haproxy/minecraft_parser.lua

defaults
    log global
    mode tcp
    option tcplog
    option dontlognull
    timeout connect 5s
    timeout client 50s
    timeout server 50s
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

# Frontend for Minecraft proxy
frontend minecraft_frontend
    bind *:{$defaultProxyPort}
    mode tcp
    option tcplog
    
    # Inspect first packet for hostname extraction
    # This allows us to read the Minecraft handshake packet
    tcp-request content accept
    tcp-request inspect-delay {$inspectDelay}s
    
    # Route based on extracted hostname
    # Note: Hostname extraction will be implemented using Lua script in Phase 3
    # For now, this is a placeholder structure
{$frontendAcls}{$defaultBackendLine}
# Backend definitions
{$backendDefs}
HAPROXY;

        return $config;
    }

    /**
     * Write Lua script to file.
     * 
     * Note: HAProxy uses chroot, so the Lua script path in the config must be relative to the chroot.
     * The chroot is typically /var/lib/haproxy, so we write the script there.
     * Uses sudo to write to protected directories.
     */
    public function writeLuaScript(): bool
    {
        if (!config('proxy.enabled', false)) {
            Log::info('Proxy functionality is disabled, skipping Lua script write');
            return false;
        }

        // HAProxy chroot is /var/lib/haproxy, so we need to place the script there
        // The path in the config should be relative to chroot: /etc/haproxy/minecraft_parser.lua
        // But we write it to the actual filesystem: /var/lib/haproxy/etc/haproxy/minecraft_parser.lua
        // OR we can write it outside chroot and use absolute path (if chroot allows)
        // Let's use the simpler approach: write to /etc/haproxy/ and reference it with absolute path
        // But HAProxy with chroot needs it inside chroot, so we'll write to both locations
        
        $luaScriptPath = '/etc/haproxy/minecraft_parser.lua';
        $chrootLuaScriptPath = '/var/lib/haproxy/etc/haproxy/minecraft_parser.lua';
        
        try {
            $luaScriptContent = File::get(resource_path('haproxy/minecraft_parser.lua'));
        } catch (\Exception $e) {
            Log::error('Failed to read Lua script source', [
                'source' => resource_path('haproxy/minecraft_parser.lua'),
                'error' => $e->getMessage(),
            ]);
            throw new \Exception("Failed to read Lua script source: {$e->getMessage()}");
        }

        try {
            // Write to temporary file first (web server can write to storage)
            $tempFile = storage_path('app/haproxy_lua_script_temp.lua');
            File::put($tempFile, $luaScriptContent);
            
            // Use sudo to copy to /etc/haproxy/ (for reference and if chroot is disabled)
            $luaScriptDir = dirname($luaScriptPath);
            $createDirCmd = "sudo mkdir -p {$luaScriptDir}";
            $copyCmd = "sudo cp {$tempFile} {$luaScriptPath}";
            $chmodCmd = "sudo chmod 644 {$luaScriptPath}";
            
            exec("{$createDirCmd} 2>&1", $output1, $returnCode1);
            if ($returnCode1 !== 0) {
                throw new \Exception("Failed to create directory: " . implode("\n", $output1));
            }
            
            exec("{$copyCmd} 2>&1", $output2, $returnCode2);
            if ($returnCode2 !== 0) {
                throw new \Exception("Failed to copy Lua script: " . implode("\n", $output2));
            }
            
            exec("{$chmodCmd} 2>&1", $output3, $returnCode3);
            if ($returnCode3 !== 0) {
                throw new \Exception("Failed to set permissions: " . implode("\n", $output3));
            }

            // Also write to chroot directory (HAProxy with chroot needs it here)
            $chrootLuaScriptDir = dirname($chrootLuaScriptPath);
            $createChrootDirCmd = "sudo mkdir -p {$chrootLuaScriptDir}";
            $copyChrootCmd = "sudo cp {$tempFile} {$chrootLuaScriptPath}";
            $chmodChrootCmd = "sudo chmod 644 {$chrootLuaScriptPath}";
            
            exec("{$createChrootDirCmd} 2>&1", $output4, $returnCode4);
            if ($returnCode4 !== 0) {
                throw new \Exception("Failed to create chroot directory: " . implode("\n", $output4));
            }
            
            exec("{$copyChrootCmd} 2>&1", $output5, $returnCode5);
            if ($returnCode5 !== 0) {
                throw new \Exception("Failed to copy Lua script to chroot: " . implode("\n", $output5));
            }
            
            exec("{$chmodChrootCmd} 2>&1", $output6, $returnCode6);
            if ($returnCode6 !== 0) {
                throw new \Exception("Failed to set chroot permissions: " . implode("\n", $output6));
            }
            
            // Clean up temp file
            File::delete($tempFile);

            Log::info('HAProxy Lua script written', [
                'script_file' => $luaScriptPath,
                'chroot_script_file' => $chrootLuaScriptPath,
            ]);

            return true;
        } catch (\Exception $e) {
            // Clean up temp file if it exists
            if (isset($tempFile) && File::exists($tempFile)) {
                File::delete($tempFile);
            }
            
            Log::error('Failed to write HAProxy Lua script', [
                'script_file' => $luaScriptPath,
                'error' => $e->getMessage(),
            ]);
            throw new \Exception("Failed to write HAProxy Lua script: {$e->getMessage()}");
        }
    }

    /**
     * Write HAProxy configuration to file.
     */
    public function writeConfig(): bool
    {
        if (!config('proxy.enabled', false)) {
            Log::info('Proxy functionality is disabled, skipping HAProxy config write');
            return false;
        }

        // First, write the Lua script
        try {
            $this->writeLuaScript();
        } catch (\Exception $e) {
            Log::warning('Failed to write Lua script, continuing with config generation', [
                'error' => $e->getMessage(),
            ]);
            // Don't fail completely - config can be written without Lua script (will fail validation though)
        }

        $configPath = config('proxy.haproxy_config_path', '/etc/haproxy/haproxy.cfg');

        // Ensure directory exists (use sudo)
        $configDir = dirname($configPath);
        if (!is_dir($configDir)) {
            $createDirCmd = "sudo mkdir -p {$configDir}";
            exec("{$createDirCmd} 2>&1", $dirOutput, $dirReturnCode);
            if ($dirReturnCode !== 0) {
                Log::error('Failed to create HAProxy config directory', [
                    'path' => $configDir,
                    'error' => implode("\n", $dirOutput),
                ]);
                throw new \Exception("Failed to create HAProxy config directory: " . implode("\n", $dirOutput));
            }
        }

        try {
            $config = $this->generateFullConfig();
            
            // Validate config before writing
            if (!$this->validateConfig($config)) {
                throw new \Exception('HAProxy configuration validation failed');
            }
            
            // Backup existing config if it exists and is different
            // Use sudo to check and backup
            if (file_exists($configPath)) {
                $existingConfig = file_get_contents($configPath);
                // Only backup if it's not our auto-generated config
                if (!str_contains($existingConfig, '# HAProxy Configuration for Pyrodactyl Subdomain Proxy')) {
                    $backupPath = $configPath . '.backup.' . date('Y-m-d_H-i-s');
                    exec("sudo cp {$configPath} {$backupPath} 2>&1", $backupOutput, $backupReturnCode);
                    if ($backupReturnCode === 0) {
                        Log::info('Backed up existing HAProxy config', [
                            'backup_file' => $backupPath,
                        ]);
                    }
                }
            }
            
            // Write config to temp file first (web server can write to storage)
            $tempConfigFile = storage_path('app/haproxy_config_temp.cfg');
            File::put($tempConfigFile, $config);
            
            // Use sudo to copy to final location
            $copyCmd = "sudo cp {$tempConfigFile} {$configPath}";
            $chmodCmd = "sudo chmod 644 {$configPath}";
            
            exec("{$copyCmd} 2>&1", $copyOutput, $copyReturnCode);
            if ($copyReturnCode !== 0) {
                throw new \Exception("Failed to copy HAProxy config: " . implode("\n", $copyOutput));
            }
            
            exec("{$chmodCmd} 2>&1", $chmodOutput, $chmodReturnCode);
            if ($chmodReturnCode !== 0) {
                throw new \Exception("Failed to set HAProxy config permissions: " . implode("\n", $chmodOutput));
            }
            
            // Clean up temp file
            File::delete($tempConfigFile);

            Log::info('HAProxy config written', [
                'config_file' => $configPath,
            ]);

            return true;
        } catch (\Exception $e) {
            // Clean up temp file if it exists
            if (isset($tempConfigFile) && File::exists($tempConfigFile)) {
                File::delete($tempConfigFile);
            }
            
            Log::error('Failed to write HAProxy config', [
                'config_file' => $configPath,
                'error' => $e->getMessage(),
            ]);
            throw new \Exception("Failed to write HAProxy config: {$e->getMessage()}");
        }
    }

    /**
     * Reload HAProxy configuration.
     */
    public function reloadHaproxy(): bool
    {
        if (!config('proxy.enabled', false)) {
            Log::info('Proxy functionality is disabled, skipping HAProxy reload');
            return false;
        }

        $command = config('proxy.haproxy_reload_command', 'sudo systemctl reload haproxy');

        try {
            $output = [];
            $returnCode = 0;
            
            // Use exec to capture output
            exec($command . ' 2>&1', $output, $returnCode);
            $output = implode("\n", $output);

            if ($returnCode === 0) {
                Log::info('HAProxy reloaded successfully', [
                    'command' => $command,
                ]);
                return true;
            } else {
                Log::error('HAProxy reload failed', [
                    'command' => $command,
                    'return_code' => $returnCode,
                    'output' => $output,
                ]);
                throw new \Exception("HAProxy reload failed: {$output}");
            }
        } catch (\Exception $e) {
            Log::error('Exception during HAProxy reload', [
                'command' => $command,
                'error' => $e->getMessage(),
            ]);
            throw new \Exception("Failed to reload HAProxy: {$e->getMessage()}");
        }
    }

    /**
     * Validate HAProxy configuration syntax.
     */
    public function validateConfig(?string $config = null): bool
    {
        $configPath = config('proxy.haproxy_config_path', '/etc/haproxy/haproxy.cfg');

        // If config is provided, write to temp file for validation
        if ($config !== null) {
            $tempFile = tempnam(sys_get_temp_dir(), 'haproxy_validate_');
            File::put($tempFile, $config);
            $configPath = $tempFile;
        }

        try {
            $command = "haproxy -c -f {$configPath} 2>&1";
            $output = [];
            $returnCode = 0;
            exec($command, $output, $returnCode);
            $output = implode("\n", $output);

            // Clean up temp file if we created one
            if ($config !== null && File::exists($tempFile)) {
                File::delete($tempFile);
            }

            if ($returnCode === 0) {
                return true;
            } else {
                Log::warning('HAProxy config validation failed', [
                    'output' => $output,
                ]);
                return false;
            }
        } catch (\Exception $e) {
            // Clean up temp file on error
            if ($config !== null && isset($tempFile) && File::exists($tempFile)) {
                File::delete($tempFile);
            }
            Log::warning('Exception during HAProxy config validation', [
                'error' => $e->getMessage(),
            ]);
            return false;
        }
    }

    /**
     * Get current timestamp in ISO 8601 format.
     */
    private function getCurrentTimestamp(): string
    {
        return (new \DateTime())->format(\DateTime::ATOM);
    }
}
